name: Cosmo build release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch: # this is a nice option that will enable a button w/ inputs
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false
env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cosmopolitan
      run: mkdir libcosmo && cd libcosmo && wget https://justine.lol/cosmopolitan/cosmopolitan.zip && unzip cosmopolitan.zip && ls -lha && cd ../
    - name: Install rust nightly toolchains
      run: rustup toolchain install nightly-x86_64-unknown-linux-gnu && rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

    - name: build
      run: ./cosmo_build.sh

    - name: compress binary
      run: cd target/x86_64-unknown-linux-cosmo/release && zip rcut.zip rcut.com && tar cvzf rcut.tar.gz rcut.com

    - name: create release  
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: rcut ${{ github.ref }}
        tag_name: gh-v-${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload rcut cosmo tgz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_path: ./target/x86_64-unknown-linux-cosmo/release/rcut.tar.gz
        asset_name: rcut-${{ github.ref }}.tar.gz
        asset_content_type: application/gzip
        # works because of previous step with id: create_release
        upload_url: ${{ steps.create_release.outputs.upload_url }}

    - name: upload rcut cosmo zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_path: ./target/x86_64-unknown-linux-cosmo/release/rcut.zip
        asset_name: rcut-${{ github.ref }}.zip
        asset_content_type: application/zip
        upload_url: ${{ steps.create_release.outputs.upload_url }}
  

